using System;
using System.IO;
using System.Text.Json;

namespace WorldDownloaderManager;

public class Settings
{
    public string DataFolder { get; set; } = "";
    public int WebPort { get; set; } = 8080;
    public int ProxyPort { get; set; } = 25565;
    public string Image { get; set; } = "ghcr.io/cafepromenade/minecraft-world-downloader:latest";
    public string ContainerName { get; set; } = "minecraft-world-downloader";
    public bool RequireLogin { get; set; } = false;
    public string Username { get; set; } = "admin";
    public string Password { get; set; } = "";

    private static string FilePath
    {
        get
        {
            var dir = Path.Combine(
                Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData),
                "WorldDownloaderManager");
            Directory.CreateDirectory(dir);
            return Path.Combine(dir, "settings.json");
        }
    }

    public static Settings Load()
    {
        Settings s = new();
        try
        {
            if (File.Exists(FilePath))
                s = JsonSerializer.Deserialize<Settings>(File.ReadAllText(FilePath)) ?? new Settings();
        }
        catch { /* fall back to defaults */ }

        if (string.IsNullOrWhiteSpace(s.DataFolder))
        {
            s.DataFolder = Path.Combine(
                Environment.GetFolderPath(Environment.SpecialFolder.UserProfile),
                "WorldDownloader");
        }
        return s;
    }

    public void Save()
    {
        try
        {
            File.WriteAllText(FilePath,
                JsonSerializer.Serialize(this, new JsonSerializerOptions { WriteIndented = true }));
        }
        catch { /* ignore */ }
    }

    /// <summary>Render a docker-compose.yml equivalent to the current settings.</summary>
    public string ToDockerCompose()
    {
        var dataPath = (DataFolder ?? "").Replace("\\", "/");
        var sb = new System.Text.StringBuilder();
        sb.AppendLine("# docker-compose.yml generated by World Downloader Manager.");
        sb.AppendLine("#");
        sb.AppendLine("# Start it from this folder with:");
        sb.AppendLine("#     docker compose up -d");
        sb.AppendLine($"# then open the web console at http://localhost:{WebPort} and point your Minecraft");
        sb.AppendLine($"# client at  localhost:{ProxyPort}.  The image launches the web console automatically");
        sb.AppendLine("# (it is the container's entrypoint) — no extra 'command:' is needed here.");
        sb.AppendLine("services:");
        sb.AppendLine("  world-downloader:");
        sb.AppendLine($"    image: {Image}");
        sb.AppendLine($"    container_name: {ContainerName}");
        sb.AppendLine("    pull_policy: always   # always fetch the latest published image so the console stays current");
        sb.AppendLine("    restart: unless-stopped");
        sb.AppendLine("    ports:");
        sb.AppendLine($"      - \"{WebPort}:8080\"      # web console -> http://localhost:{WebPort}");
        sb.AppendLine($"      - \"{ProxyPort}:25565\"    # Minecraft proxy -> connect to localhost:{ProxyPort}");
        sb.AppendLine("    environment:");
        sb.AppendLine("      WEB_PORT: \"8080\"");
        if (RequireLogin)
        {
            sb.AppendLine($"      WEB_USERNAME: \"{Username}\"");
            sb.AppendLine($"      WEB_PASSWORD: \"{Password}\"");
        }
        sb.AppendLine("    volumes:");
        sb.AppendLine($"      - \"{dataPath}:/data\"");
        return sb.ToString();
    }

    /// <summary>Write docker-compose.yml into the data folder; returns the file path.</summary>
    public string WriteDockerCompose()
    {
        Directory.CreateDirectory(DataFolder);
        var path = Path.Combine(DataFolder, "docker-compose.yml");
        File.WriteAllText(path, ToDockerCompose());
        return path;
    }
}
